### ISSUE TITLE
Build fails on mac

### ISSUE THREAD

**Issue by qpwo** [NivenT/Planet#1]
I followed the build instructions in the readme.md:

```
git clone https://github.com/NivenT/Planet
cd Planet
git submodule update --init --recursive
mkdir build
cd build
cmake ../
```
But it failed at the cmake stage:
```
-- C++14 is supported.
-- Checking compiler flags for C++14 support.
-- C++14 is supported.
CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  jubilant-funicular/cmake/FindSDL2.cmake:148 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  jubilant-funicular/CMakeLists.txt:47 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/lhm/Planet/build/CMakeFiles/CMakeOutput.log".
```

What should I do to get this working?

**Comment by NivenT** [comment]
This is being handled privately, but seeing as how it's been nearly a month, this might be a good time to mention generally what the problem/solution is before I forgot too much.

The specific error mentioned above is a missing dependency, which can be gotten using `brew`. In response,I have tried to be a little more clear about what's needed in the readme, and have opted to include a few dependencies in this (or the jubilant-funicular) repo to making getting everything a little easier since there are a lot.

Unfortunately, issues did not stop there. The next major thing I can think of was an error that showed up in clang, but is accepted by gcc. The error was essentially what's [described here](https://stackoverflow.com/questions/37493026/why-does-this-code-compile-with-gcc-but-not-with-clang), and in this instance it is caused by a design choice in jubilant-funicular. To fix it here, I just commented out the offending code since it was just a couple of print statements that weren't all that important.

At the moment, there's an issue with the game not rendering properly (or at all) on os x. We're currently trying to figure out why that is the case.

**Comment by NivenT** [comment]
Looks like we got things working. There were possibly a few issues causing it to not run on os x, but the main one was a [bug](https://github.com/NivenT/jubilant-funicular/commit/7fa991e70e20ee220561fd4a56f6c2e8a9c5c8a6) in jubilant-funicular where shader attributes were never properly set up.
